name: BlockSwap
author: Jaerry
main: com.jaerry.BlockSwap.BlockSwap
version: 1.3.8
api-version: 1.16
commands:
  BlockSwap:
    description: Enters you into the BlockSwap game
    permission: jaerry.basic
    permission-message: You don't have jaerry.basic permission
  BSStart:
    description: Enters you into the BlockSwap game
    permission: jaerry.basic
    permission-message: You don't have jaerry.basic permission
  BSEnd:
    description: Enters you into the BlockSwap game
    permission: jaerry.basic
    permission-message: You don't have jaerry.basic permission